services:
  telegram_bot:
    build:
      context: .
    container_name: telegram_cbs_bot_sqlite
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      SQLITE_DB_PATH: /app/data/bot.sqlite3
    volumes:
      - ./data:/app/data